apiVersion: v1
kind: Secret
metadata:
  name: gcs-minio-secret
  namespace: kubeflow-user-example-com
type: Opaque
data:
  gcloud-application-credentials.json: <BASE64_ENCODED_JSON_CREDENTIALS> # Replace with your base64 encoded GCP service account JSON credentials